language: php
sudo: false

php:
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'
  - '8.0snapshot'

before_script:
  - composer update

script:
  - ./vendor/bin/phpunit
  - ./vendor/bin/phpcs --standard=PSR2 -n src
  - ./vendor/bin/psalm
  - ./vendor/bin/parallel-lint src
